TT-2437 add mnemonic with-index to kms signatures for LTC and BTC
tatumio/tatum-kms pull request #47
Opened 2022-09-19 12:16 UTC by pedrodbaptista

- add mnemonic with-index to kms signatures for LTC and BTC
- remove LUNA

2022-09-19 17:19 UTC, alexloiko commented on src/management.ts
> +    console.error(JSON.stringify({ error: `No such wallet for chain '${chain}'.` }, null, 2))
Let's extract common code of wallet read

2022-09-19 17:19 UTC, alexloiko commented on src/management.ts
> +    console.error(JSON.stringify({ error: `No such wallet for chain '${chain}'.` }, null, 2))
please extract common log method, to have just log('some message')

2022-09-19 17:19 UTC, alexloiko commented on src/signatures.ts
> +          if (w.mnemonic !== undefined && s.index !== undefined && s.index !== null) {
please use _.isNil() from lodash and extract condition to named variable

2022-09-19 17:19 UTC, alexloiko commented on src/management.ts
> +    const wallets: any[] = Object.values(walletData ?? {}).filter(w => w?.chain === chain && w?.mnemonic !== null && w?.mnemonic !== undefined)
please use _.isNil()

2022-09-19 17:19 UTC, alexloiko commented on src/signatures.ts
> +  let wallets: any[] = []
try not to use explicit any

2022-09-19 17:19 UTC, alexloiko commented on src/signatures.ts
> +        (await signAlgoKMSTransaction(transaction, algoSecret, testnet)) as string,
is it expected change?

2022-09-20 07:12 UTC, pedrodbaptista commented on src/management.ts
> +    console.error(JSON.stringify({ error: `No such wallet for chain '${chain}'.` }, null, 2))
makes total sense

2022-09-20 07:15 UTC, pedrodbaptista commented on src/management.ts
> +    console.error(JSON.stringify({ error: `No such wallet for chain '${chain}'.` }, null, 2))
I already change above, but we can talk about this to have a better logger

2022-09-20 07:18 UTC, pedrodbaptista commented on src/signatures.ts
> +          if (w.mnemonic !== undefined && s.index !== undefined && s.index !== null) {
done

2022-09-20 07:34 UTC, pedrodbaptista commented on src/management.ts
> +    const wallets: any[] = Object.values(walletData ?? {}).filter(w => w?.chain === chain && w?.mnemonic !== null && w?.mnemonic !== undefined)
done

2022-09-20 07:36 UTC, pedrodbaptista commented on src/signatures.ts
> +  let wallets: any[] = []
just remove it.

2022-09-28 18:17 UTC, samuelsramko requested changes

2022-09-28 18:17 UTC, samuelsramko commented on src/signatures.ts
> +      signatures?.forEach(async (s: Signature) => {
dont use .forEach and async -> replace with for...of and await inside.

2022-09-28 18:17 UTC, samuelsramko commented on src/signatures.ts
> +function getPrivateKeys(wallets: ParcialWallet[], signatures: Signature[], currency: Currency): string[] {
replace with arrow function and const

2022-09-28 18:17 UTC, samuelsramko commented on src/signatures.ts
> +  if (blockchainSignature.signatures && blockchainSignature.signatures.length > 0) {
replace with  (blockchainSignature?.signatures?.length > 0)

2022-09-28 18:17 UTC, samuelsramko commented on src/signatures.ts
> +      console.log('privatekeys', privateKeys, wallets, signatures)
remove console.log

2022-09-29 08:54 UTC, samuelsramko commented on src/interfaces.ts
> +export interface ParcialWallet {
dont like naming here - not descriptive enough

2022-09-29 08:55 UTC, samuelsramko commented on src/signatures.ts
> +  if (!wallets || (wallets && wallets.length === 0)) {
again - if (!wallets?.length)

2022-09-29 09:10 UTC, pedrodbaptista commented on src/signatures.ts
> +  if (!wallets || (wallets && wallets.length === 0)) {
make sense, thanks

2022-09-29 09:12 UTC, pedrodbaptista commented on src/interfaces.ts
> +export interface ParcialWallet {
actually you made me noticed that we have same naming in 2 interfaces (need to change both)

2022-09-29 09:57 UTC, samuelsramko approved these changes

2022-09-29 09:57 UTC, merged