added a Dockerfile and dockerignore file
tatumio/tatum-kms pull request #5
Opened 2021-08-05 19:50 UTC by samuelbartels20

Please review the work done for Dockerfile

2021-08-06 06:57 UTC, samuelsramko requested changes

2021-08-06 06:57 UTC, samuelsramko commented on Dockerfile
> +EXPOSE 8080
port is not needed to expose

2021-08-06 06:57 UTC, samuelsramko commented on Dockerfile
> +FROM node:14
please add section to the README - how to operate km from docker. examples of tatum-kms daemon mode and also CLI mode.

2021-08-06 16:46 UTC, samuelbartels20 commented on Dockerfile
> +EXPOSE 8080
I have deleted the port

2021-08-06 17:55 UTC, samuelbartels20 commented on Dockerfile
> +FROM node:14
Please check the documentation for the new changes

2021-08-06 18:01 UTC, samuelbartels20 reviewed
Please check the documentation for the new changes

2021-08-06 18:09 UTC, samuelsramko requested changes

2021-08-06 18:09 UTC, samuelsramko commented on README.md
> +docker build . -t [your prefered image name]
we will provide our docker image - docker pull @tatumio/tatum-kms. Please, update examples for that particular image

2021-08-06 18:09 UTC, samuelsramko commented on README.md
> +sudo docker run -d [Docker image ID or name]
this run will ru tatum-kms daemon by default? and when you want to generate wallets, you will exec to the docker shell? we also need to add docker volume, so wallet.dat file will be available from outside - it cant be lost.

2021-08-09 08:02 UTC, tholcman commented on Dockerfile
> +FROM node:14
I would also suggest to use `14-alpine` to keep image as small as possible. But this will require to try functionality as there are some differences on OS level

2021-08-09 08:03 UTC, samuelsramko commented on Dockerfile
> +
we can do it as a root inside docker, don't think it makes a difference actually. but nice to have

2021-08-09 11:51 UTC, tholcman commented on Dockerfile
> +
even 

> ... root inside docker ...

is considered as security bad practice and yes it makes a difference.

2021-08-09 11:58 UTC, samuelsramko commented on Dockerfile
> +
so use custom user instead of ROOT

2021-08-12 06:35 UTC, samuelsramko commented
Close because of https://github.com/tatumio/tatum-kms/pull/6 is handling this logic as well. Move there

2021-08-12 06:35 UTC, closed without merging